"""add is_url_valid to news

Revision ID: 15d4dc47b840
Revises: c2e2c60b18de
Create Date: 2023-03-04 13:36:16.965496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d4dc47b840'
down_revision = 'c2e2c60b18de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_url_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_url_valid')
    # ### end Alembic commands ###
