"""Add parse_errors table

Revision ID: 9ffede6c5d9a
Revises: fd3cf83f9f45
Create Date: 2023-03-03 22:51:31.199290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffede6c5d9a'
down_revision = 'fd3cf83f9f45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parse_errors_id'), 'parse_errors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parse_errors_id'), table_name='parse_errors')
    op.drop_table('parse_errors')
    # ### end Alembic commands ###
