"""Nullable is false for link in parse_errors and news

Revision ID: c2e2c60b18de
Revises: 9ffede6c5d9a
Create Date: 2023-03-03 23:13:19.582843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2e2c60b18de'
down_revision = '9ffede6c5d9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'link',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('parse_errors', 'link',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parse_errors', 'link',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('news', 'link',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
