"""Add unique constraint to news.link

Revision ID: fd3cf83f9f45
Revises: 8d1bd8ba6387
Create Date: 2023-03-01 20:07:31.643807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3cf83f9f45'
down_revision = '8d1bd8ba6387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'news', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    # ### end Alembic commands ###
